apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tokenflow.fullname" . }}-policy
  labels:
    {{- include "tokenflow.labels" . | nindent 4 }}
data:
  policy.yaml: |-
    {{- .Values.policy.content | nindent 4 }}
